service:
  nameSpace: (Quadratic Roots)
  subSystem: CMD
grpc:
  port: :5001
  development: true
http:
  port: :5007
  development: true
  basePath: /api/v1
  appPath: /api/v1/qr-cmd
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: short-caller-console
jaeger:
  enable: true
  serviceName: qr-cmd
  hostPort: "jaeger:6831"
  logSpans: false
eventStoreDb:
  connectionString: "esdb://eventstore:2113?tls=false"
redis:
  url: "redis://redis:6379/0"
projection:
  poolSize: 60
  eventPrefix: "qr-"
  group: "qr-med"
  name: "qr.Projector"
nats:
  url: "nats://core-nats:4222"
  user: "a"
  password: "a"