package constants

const (
	GrpcPort                   = "GRPC_PORT"
	HttpPort                   = "HTTP_PORT"
	ConfigPath                 = "CONFIG_PATH"
	KafkaBrokers               = "KAFKA_BROKERS"
	JaegerHostPort             = "JAEGER_HOST"
	RedisAddr                  = "REDIS_ADDR"
	EventStoreConnectionString = "EVENT_STORE_CONNECTION_STRING"
	ElasticUrl                 = "ELASTIC_URL"
	NatsUrl                    = "NATS_URL" //
	CouchDbUri                 = "COUCH_URI"
	MongoDbUri                 = "MONGO_URI"
	MongoDbUser                = "MONGO_USER"
	MongoDbPassword            = "MONGO_PASSWORD"
	MongoDbAuthMechanism       = "MONGO_AUTH_MECHANISM"
	ReaderServicePort          = "READER_SERVICE"
	RedisUrl                   = "REDIS_URL"

	Yaml          = "yaml"
	Tcp           = "tcp"
	Redis         = "redis"
	Kafka         = "kafka-events"
	Postgres      = "postgres"
	MongoDB       = "mongo"
	ElasticSearch = "elasticSearch"
	EventStore    = "eventStore"
	Nats          = "nats"

	GRPC     = "GRPC"
	SIZE     = "SIZE"
	URI      = "URI"
	STATUS   = "STATUS"
	HTTP     = "HTTP"
	ERROR    = "ERROR"
	METHOD   = "METHOD"
	METADATA = "METADATA"
	REQUEST  = "REQUEST"
	REPLY    = "REPLY"
	TIME     = "TIME"

	Topic        = "topic"
	Partition    = "partition"
	Message      = "message"
	WorkerID     = "workerID"
	Offset       = "offset"
	Time         = "time"
	GroupName    = "GroupName"
	StreamID     = "StreamID"
	EventID      = "EventId"
	EventType    = "EventType"
	EventNumber  = "EventNumber"
	CreatedDate  = "CreatedDate"
	UserMetadata = "UserMetadata"

	Page   = "page"
	Size   = "size"
	Search = "search"
	ID     = "id"

	EsAll = "$all"

	Validate        = "validate"
	FieldValidation = "field validation"
	RequiredHeaders = "required header"
	Base64          = "base64"
	Unmarshal       = "unmarshal"
	Uuid            = "uuid"
	Cookie          = "cookie"
	Token           = "token"
	Bcrypt          = "bcrypt"
	SQLState        = "sqlstate"

	MongoProjection    = "(MongoDB Projection)"
	ElasticProjection  = "(Elastic Projection)"
	CouchProjection    = "(Couch DB Projection)"
	RedisProjection    = "(Redis DB Projection)"
	MediatorProjection = "(Mediator Projection)"

	Nil = "nil"
)
