service:
  nameSpace: SDK
  subSystem: CMD
grpc:
  port: :5001
  development: true
http:
  port: :5007
  development: true
  basePath: /api/v1
  appPath: /api/v1/sdk
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: short-caller-console
jaeger:
  enable: true
  serviceName: sdk
  hostPort: "localhost:6831"
  logSpans: false
eventStoreDb:
  connectionString: "esdb://localhost:2113?tls=false"
redis:
  url: "redis://localhost:6379/0"
projection:
  poolSize: 6
  eventPrefix: "sdk-"
  group: "sdk-med"
  name: "sdkProjector"
nats:
  url: "nats://localhost:4222"
  user: "a"
  password: "a"
cockroach_db:
  dsn: "postgresql://localhost:26257/defaultdb?sslmode=disable"
kafka:
  bootstrapServers: "localhost:9092"
  groupId: "sdk-group"
  autoOffsetReset: "earliest"
  retentionMs: "1000"
mongoDb:
  uri: "mongodb://localhost:27017"
  user: root
  password: changeme

